---

- name: install dependencies
  apt:
    name: "{{ dependencies.encryption }}"
    state: latest
    update_cache: no # skip cache check since we already ran apt

- name: add dependencies to install list
  set_fact:
    install_packages: "{{ install_packages + dependencies['encryption'] }}"

- name: fetch cryptsetup version
  command: "cryptsetup --version"
  changed_when: no
  register: _cryptsetup_version

- name: register version
  set_fact:
    cryptsetup_version: "{{ _cryptsetup_version.stdout[11:] }}"

- block:
  - name: set encryption targets (partition)
    set_fact:
      _encrypt_targets: "{{ _encrypt_targets|default({})|combine({item.key: item.value}) }}"
    no_log: true
    with_dict: "{{ _tgt_devices }}"
    when: item.value['encrypt']|default(False)

  - name: create encrypted devices
    command: >
      cryptsetup -q --cipher {{ item.value['cipher']|default('aes-xts-plain64') }}
      --type {{ item.value['luks-type']|default(luks_type) }}
      {{ luks_sector_size if luks_version|int == 2 else '' }}
      --key-size {{ item.value['key-size']|default('256') }} --hash {{ item.value['hash']|default('sha512') }}
      --iter-time {{ item.value['iter-time']|default('5000') }} 
      {{ item.value.encrypt_params | d([]) | join(' ') }}
      luksFormat {{ item.key }}
    args:
      stdin: "{{ item.value['passphrase'] }}"
    no_log: true
    vars:
      luks_version: "{{ 2 if cryptsetup_version[0]|int >= 2 else 1 }}"
      luks_type: "{{ 'luks2' if luks_version|int == 2 else 'luks' }}"
      luks_sector_size: "--sector-size {{ item.value['luks-sector-size']|default(4096) }}"
    loop_control:
      label: "{{ item.key }}"
    with_dict: "{{ _encrypt_targets|default({}) }}"

  - name: fetch luks UUID for device
    command: "cryptsetup luksUUID {{ item.key }}"
    no_log: true
    register: _luksuuid
    with_dict: "{{ _encrypt_targets|default({}) }}"

  - name: store data for target devices
    set_fact:
      _tgt_devices: >
        {{ _tgt_devices|combine({'/dev/mapper/' +  item.item.value['target']:
        item.item.value|combine({'luksuuid': item.stdout, 'encrypt': None,
        'passphrase': None, 'target': None, 'use_dev': True})}) }}
    no_log: true
    with_items: "{{ _luksuuid.results }}"

  - name: open luks Devices
    command: >
      cryptsetup -q luksOpen --allow-discards {{ item.key }} {{ item.value['target'] }}
    args:
      stdin: "{{ item.value['passphrase'] }}"
    loop_control:
      label: "{{ item.key }}"
    with_dict: "{{ _encrypt_targets|default({}) }}"
    register: _luksopen

  - name: create folder for on keyfiles
    ansible.builtin.file:
      path: "{{ item.value.keyfile | dirname }}"
      state: directory
      owner: root
      group: root
      mode: "0400"
    loop_control:
      label: "{{ item.value.keyfile | default('Null') }}"
    with_dict: "{{ _encrypt_targets|default({}) }}"
    when: item.value.keyfile is defined | default(false)
    #when: item.value | selectattr("keyfile", "defined") | list | length > 0 

  - name: Create keyfile
    ansible.builtin.command:
      cmd: dd if=/dev/urandom of={{ item.value.keyfile }} bs=2048 count=2 iflag=fullblock
      creates: "{{ item.value.keyfile }}"
    loop_control:
      label: "{{ item.value.keyfile | default('Null') }}"
    with_dict: "{{ _encrypt_targets|default({}) }}"
    when: item.value.keyfile is defined | default(false)

  - name: Set permissions on keyfile 
    ansible.builtin.file:
      path: "{{ item.value.keyfile }}"
      owner: root
      group: root
      mode: "0400"
    loop_control:
      label: "{{ item.value.keyfile | default('Null') }}"
    with_dict: "{{ _encrypt_targets|default({}) }}"
    when: item.value.keyfile is defined | default(false)

  - name: Add keyfile
    community.crypto.luks_device:
      name: "{{ item.value['target'] }}"
      state: "present"
      passphrase: "{{ item.value['passphrase'] }}"
      new_keyfile: "{{ item.value.keyfile }}"
    loop_control:
      label: "{{ item.value.keyfile | default('Null') }}"
    with_dict: "{{ _encrypt_targets|default({}) }}"
    when: item.value.keyfile is defined | default(false)

  rescue:
  - include_tasks: cleanup.yml
  - include_tasks: wipe.yml
  - fail:
      msg: "Setting up Encryption failed"
